name: Deploy to Server

on:
  push:
    branches:
      - main   # change if your branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 23.94.230.146
          username: hrati1027
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/hr3.atierahotelrestaurant.com/public_html/subdomain
            git reset --hard
            git pull origin main
